# Generated by Django 3.0.6 on 2020-06-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dreamuser',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_followed_by', to='userprofiles.DreamUser'),
        ),
    ]
