# Generated by Django 3.0.6 on 2020-06-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0002_auto_20200608_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='dreamuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile-image'),
        ),
    ]
