# Generated by Django 3.0.6 on 2020-06-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('top', models.CharField(max_length=120)),
                ('bottom', models.CharField(max_length=120)),
                ('shoes', models.CharField(max_length=120)),
                ('jacket', models.CharField(blank=True, max_length=120)),
                ('socks', models.CharField(blank=True, max_length=120)),
                ('hat', models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
