# Generated by Django 3.0.6 on 2020-06-04 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothing', '0005_auto_20200603_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=20)),
                ('cut', models.CharField(max_length=60)),
                ('pattern', models.CharField(max_length=60)),
                ('texture', models.CharField(max_length=60)),
                ('brand_example', models.CharField(max_length=60)),
                ('link_example', models.CharField(max_length=60)),
                ('cost_of_example', models.FloatField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
