# Generated by Django 3.0.6 on 2020-06-05 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='brand_example',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='cost_of_example',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='cut',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='link_example',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='pattern',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='article',
            name='texture',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
