# Generated by Django 3.0.6 on 2020-06-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_auto_20200605_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cost_of_example',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
