# Generated by Django 3.0.6 on 2020-06-08 20:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothing', '0009_auto_20200605_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='article_favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
