# Generated by Django 3.0.6 on 2020-06-08 20:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothing', '0010_article_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='outfit_favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
