# Generated by Django 3.0.6 on 2020-06-08 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0012_outfit_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='bottom',
        ),
        migrations.AddField(
            model_name='outfit',
            name='bottom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_bottom', to='clothing.Article'),
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='shoes',
        ),
        migrations.AddField(
            model_name='outfit',
            name='shoes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_shoes', to='clothing.Article'),
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='top',
        ),
        migrations.AddField(
            model_name='outfit',
            name='top',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfit_top', to='clothing.Article'),
        ),
    ]
