# Generated by Django 3.0.6 on 2020-06-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0013_auto_20200608_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='favorited_by',
            new_name='favorited',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='favorited_by',
            new_name='favorited',
        ),
    ]
