# Generated by Django 3.0.6 on 2020-06-11 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_auto_20200608_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
