# Generated by Django 3.0.6 on 2020-06-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0015_outfit_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='actual_location',
            field=models.CharField(choices=[('TOP', 'Top'), ('BTM', 'Bottom'), ('SHS', 'Shoes')], default='None', max_length=60, null=True),
        ),
    ]
