# Generated by Django 3.0.6 on 2020-06-17 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0016_article_actual_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('articles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_in_collection', to='clothing.Article')),
                ('outfits', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outfits_in_collection', to='clothing.Outfit')),
            ],
        ),
    ]
