# Generated by Django 3.0.6 on 2020-06-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0017_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='articles',
        ),
        migrations.AddField(
            model_name='collection',
            name='articles',
            field=models.ManyToManyField(null=True, related_name='articles_in_collection', to='clothing.Article'),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='outfits',
        ),
        migrations.AddField(
            model_name='collection',
            name='outfits',
            field=models.ManyToManyField(null=True, related_name='outfits_in_collection', to='clothing.Outfit'),
        ),
    ]
