# Generated by Django 3.0.6 on 2020-06-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0019_collection_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='articles',
            field=models.ManyToManyField(related_name='articles_in_collection', to='clothing.Article'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='outfits',
            field=models.ManyToManyField(related_name='outfits_in_collection', to='clothing.Outfit'),
        ),
    ]
