# Generated by Django 3.0.6 on 2020-07-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0020_auto_20200617_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to='article-image'),
        ),
    ]
