# Generated by Django 3.0.6 on 2020-07-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0021_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='image',
            field=models.ImageField(blank=True, upload_to='outfit-image'),
        ),
    ]
